version: '3'
services:
  db:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
    volumes:
      - 'sql:/bitnami'
    restart: on-failure
  php-fpm:
    image: 'shingo0620/php:${PHP_VERSION}-fpm'
    environment:
      - JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK=1
    volumes:
    - ./src:/var/www/html
    depends_on:
      - db
    restart: on-failure
  web:
    image: bitnami/nginx:latest
    ports:
      - '8080'
    volumes:
      - ./config/my_server_block.conf:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro
      - ./certs:/certs
      - ./src:/var/www/html
    depends_on:
      - php-fpm
    restart: on-failure
  src:
    build: ./src
    image: ${PROJECT}:${VERSION}
    volumes:
      - './src:/var/www/html'
    tty: true
volumes:
  sql: