version: '3'
services:
  db:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    volumes:
      - 'sql:/bitnami'
    restart: on-failure
  php-fpm:
    image: 'shingo0620/php:${PHP_VERSION}-fpm'
    environment:
      - JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK=1
    volumes:
      - site:/var/www/html
    depends_on:
      - db
    restart: on-failure
  web:
    build: .
    image: ${PROJECT}:${VERSION}
    ports:
      - '80'
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/certs
      - site:/var/www/html
    depends_on:
      - php-fpm
    restart: on-failure
    env_file:
      - .env
volumes:
  sql:
  site: