apiVersion: skaffold/v1
kind: Config
metadata:
  name: example-website
build:
  artifacts:
  - image: asia.gcr.io/tellustek-k8s/example/website
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-manifests/secrets.yaml
    - k8s-manifests/pvc.yaml
    - k8s-manifests/service_ingress.yaml
    - k8s-manifests/deployment.yaml
