apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: example
  name: website-pv
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 3Gi
  # accessModes:
  # - ReadWriteMany
  # nfs:
  #   server: nfs-server.default.svc.cluster.local
  #   path: "/exports"