apiVersion: v1
kind: Service
metadata:
  namespace: example
  name: website
spec:
  type: NodePort
  selector:
    project.name: example-website
  ports:
  - name: "http"
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Secret
metadata:
  namespace: example
  name: www.example.com-tls
data:
  tls.crt: <CERT_IN_BASE64>
  tls.key: <KEY_IN_BASE64>
type: kubernetes.io/tls

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: example
  name: website
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - www.example.com
    secretName: www.example.com-tls
  rules:
  - host: www.example.com
    http:
      paths:
      - backend:
          serviceName: website
          servicePort: 80
