apiVersion: v1
kind: Service
metadata:
  namespace: tellustek
  name: website
spec:
  type: NodePort
  selector:
    project.name: tellustek-website
  ports:
  - name: "http"
    port: 80
    targetPort: 80

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: tellustek
#   name: website-tls
# data:
#   tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvakNDQW9vQ0NRQ0VGTjRDVVBjZVFqQU5CZ2txaGtpRzl3MEJBUXNGQURDQmtqRUxNQWtHQTFVRUJoTUMKVkZjeER6QU5CZ05WQkFnTUJsZGhibWgxWVRFUE1BMEdBMVVFQnd3R1ZHRnBjR1ZwTVJJd0VBWURWUVFLREFsVQpaV3hzZFhOMFpXc3hEREFLQmdOVkJBc01BMWRsWWpFYU1CZ0dBMVVFQXd3UmF6aHpMblJsYkd4MWMzUmxheTVqCmIyMHhJekFoQmdrcWhraUc5dzBCQ1FFV0ZITm9hVzVuYjBCMFpXeHNkWE4wWldzdVkyOXRNQjRYRFRFNU1URXkKTnpBM05EVXdPRm9YRFRJNU1URXlOREEzTkRVd09Gb3dnWkl4Q3pBSkJnTlZCQVlUQWxSWE1ROHdEUVlEVlFRSQpEQVpYWVc1b2RXRXhEekFOQmdOVkJBY01CbFJoYVhCbGFURVNNQkFHQTFVRUNnd0pWR1ZzYkhWemRHVnJNUXd3CkNnWURWUVFMREFOWFpXSXhHakFZQmdOVkJBTU1FV3M0Y3k1MFpXeHNkWE4wWldzdVkyOXRNU013SVFZSktvWkkKaHZjTkFRa0JGaFJ6YUdsdVoyOUFkR1ZzYkhWemRHVnJMbU52YlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQU9XcVJoRzA1bVdnQmR0T1M2dW44Qk9Vcjg4a0hza2EzMU5wVy9Xc242bFVvbFh5CnhyNjJ1SFFBeXdQeXFNOFM1T0NSTjRRR2lYd1Q4L2liLzFobktlcStWOE9tSi8zZkxjSUFRM2FDM1U0YWJKMTYKYUVjbjU1L1dMTmkxbGNwWDJXT3B5V2xPMDlHNlN1QU80V1loTFhEU0xzaHVLa0Z5TkNBNFVqNlVMUS8zMUhnVgowVjZmV3NxbW9GUUF1S2JyVEQ3M1lFajhSa0dJNU9JcGhHdDkxUDNSb0Zyb2tJc0Vqd3JGaGpUWGJpa2ZGRnAzCjM0dmhkT0RVOWZmdWx4dWwwUENWbk4zdkZBRS9rZjEybWRvVXZSMnFycGxtajNMZFhLQkx2UWZMOWRVcG1GRnYKK3dJWXkxcElaSEJZWGdVZWFjNDhhSncvUXV2VFFGT2FHRVJyV2JrQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRgpBQU9DQVFFQXp3aFY2WmQxUzU5Vi8zYk1wSUhabkhkZTMwSkRmanU0bHNBUUh2UW5wZjlFZlFIQXBwNzA0dU84Cjc5b3NLVDN3Tm5INUtMWURQSXdEdGk4Zm5SVmpENDJPUFZPb1JENnlCVDdvRHRzbFplcXI1VytlVzZ4b2FHY2oKTFBxODZyR3M5Z3g1VjBrYjY1SDRYQmc5c3lDTEd1dHZkb1RJVWFYUERtRFBrTk83QUp4YzhTbVpMN2FrektsaApJYmx4S0VaTXd2OThpWlBMWURhYzJoZHdPRlAvNktpNGxIS3l3NzgvNEFmL1dnM2NzNXZ5YjBvNU53QlBWc0pkCkNNd0FvWEQrUmZzNEEvczRMZlMyeFppTnE5cElwVkdxNFFYbGI5M1BwcHQwUWJwclFTc0IwbDFweHJXYUhhUDcKUDZUL1h2MkdUajNGTFIxbkRaOXpQekU5WW0xelFnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
#   tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRGxxa1lSdE9abG9BWGIKVGt1cnAvQVRsSy9QSkI3Skd0OVRhVnYxckorcFZLSlY4c2ErdHJoMEFNc0Q4cWpQRXVUZ2tUZUVCb2w4RS9QNAptLzlZWnlucXZsZkRwaWY5M3kzQ0FFTjJndDFPR215ZGVtaEhKK2VmMWl6WXRaWEtWOWxqcWNscFR0UFJ1a3JnCkR1Rm1JUzF3MGk3SWJpcEJjalFnT0ZJK2xDMFA5OVI0RmRGZW4xcktwcUJVQUxpbTYwdys5MkJJL0VaQmlPVGkKS1lScmZkVDkwYUJhNkpDTEJJOEt4WVkwMTI0cEh4UmFkOStMNFhUZzFQWDM3cGNicGREd2xaemQ3eFFCUDVIOQpkcG5hRkwwZHFxNlpabzl5M1Z5Z1M3MEh5L1hWS1poUmIvc0NHTXRhU0dSd1dGNEZIbW5PUEdpY1AwTHIwMEJUCm1oaEVhMW01QWdNQkFBRUNnZ0VCQUtvUE8zTkJFSm1QdE1aL1kyam9JYzFkL0JEV0hqV3J3Rkp6WWJTNDdrRGsKZXBCS0JRQ1RMR0k1ZEJxb1JIZVE5Z21UZmhnMC92anhqV1k1blFwSTJiRUk0TlB1NVE0SGhFcHpCNEZweFpWZgoyNjJBUmxicUpZa2xmbSs1aGdFZXE4b3dud05yYTAyUk5JQlVoSEtyZm9wY0dHZ3hxdmhyS0UzelpuTVFKWTM3Ci9iZG03MGU4a0dXZEZ5Uzd4MTdJbmNoM2ZsdUxVd1ZzUWRkeFBZODljOUlSdGNXSWZYTlZCK3R6SHRhOFk0Y3MKNUNqQUVsZDNmTUJrMDVBZWJPUGZReGxlZmViRXQ3QVd6VSs0QnB0MVY5R0NnZXJCSG9HakdDQjkzYUJGQVJwdQo5VFE3Z3RwL3QvSEFlTWR0cTdRSXhPSkl6Qmt4QkhuLzZaTHd2d3hDWVFFQ2dZRUEvelAxa205dHpEcU1zRFdSCjZyWDBDQ3pMOG5Md05KWDgwRUM4UGdzeVQ3UlpiQVpqWUNXcGtNQ0I3QXF1K3JndmR2RlFhSUF6SmdkNlNWdDAKbDVSOEwzM3h0Y1hxd01MK01DVkorTkhqeHNUT3QzTjhZd3R6alFOSW9ZaHRVemJtVXdYMDE5VzBWQWtmNWVWVQo1OUhOSlNQRGx6VWlhNEl1dU91V2tUOEJvT1VDZ1lFQTVtSGxkdngza2UxM1pDcDh3SGNWMXEweGpmcDFmNCt5CmgraDZ3TmhZVllRdnFNVkxXeUIzek9rajVXYmV5N1c1U0dLaDlsOXhiZ21LZ3M0REFNZ3N0NFF3SlRBa2szTXYKYXV6K2dyWlhBdmpBaEFqSGJ5ZFhjWkUvalIzSW8vaStsbzlXdUxVSHh0R1QrSGRseHVIdGRHRjVWVHVUTUh4eApHNFdWMy8vclRFVUNnWUVBcitPdTRHTmVTSUVlRUNDTDFqbmIzSHFMZ2ltSHRxYWRYU2NRMXE0KzJjSlNVMnEvCnVUZWIrOEZDaWwzK3BaeW1VaE1WdVVDS2dDNXRNUHdRaXB4elR3UTl3R3VOVlpmUE8zMm4wdzlPTHVQY0dZSkYKKzdtYnhWZTdDbUlOLzJsNkswU1NzT09BYXQ3ekZpOE9hc3dsMlBBaVVTZjA5aVgrYjhNbnZpbXZ4S1VDZ1lCMApqcER1bXhyUGpLbjcxbmNaVk9hS24wTlVCcVJOcm1EdjI5SEhJVzNIamtJaWkvYnRHc2NodDg1K2NJWkY0Q0htCm1taEE0dGJiaWg0MndZM0pabjBoTjlLMzdkeURjU0pMWWEzK2Fjd3A1N3BXMHE0NzhWYVBVYUlxZmlnVnRYS1AKYitPN1BYTzZ4aXVyNkpSb2c4T0VQeENJNjhReklyS0M3eG45bzFmalZRS0JnSCtQZ1U3eUw2eTJaN3NkajdzcQptc3lBV3U3L3VDTWRGWXhCeldkcWRObDRKK1ZQOGVZaDNhaGdMUkRoQ3VMR21TVG5xY2JQWUpkRlZmbkVCY1o5CmIwcENZYUcrd2l0L1Nsa01VMjE2emMwNEVnd2YreWI0anB5aytuUTdVMWxXS1FKQWFNZ0dtemxIdVA3cnVKOTQKMFpRa2JpZVFKS1Q2YVJMSVh4NzJYVGRxCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
# type: kubernetes.io/tls

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: tellustek
  name: website
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  # tls:
  # - hosts:
  #   - k8s.tellustek.com
  #   secretName: website-tls
  rules:
  - host: k8s.tellustek.com
    http:
      paths:
      - backend:
          serviceName: website
          servicePort: 80
  - host: www.tellustek.com
    http:
      paths:
      - backend:
          serviceName: website
          servicePort: 80